### ISSUE TITLE
VSIX install fails on system with VS Code (and Visual Studio 2017)

### ISSUE THREAD

**Issue by charliearcuri** [matthewfcarlson/musupport#28]
VSIX install failed - not installable on any currently installed products

REPRO STEPS
  1) install musupport-0.0.6.vsix on my machine that has Visual Studio Code installed.
EXPECTED
  Success!  I can F12 to go to definition of various things defined in Mu/UEFI.
ACTUAL
  Install fails.  Screenshot and Log attached.

[dd_VSIXInstaller_20190930110336_40b0.log](https://github.com/matthewfcarlson/musupport/files/3672627/dd_VSIXInstaller_20190930110336_40b0.log)
![VSIX install failed - not installable on any currently installed products](https://user-images.githubusercontent.com/2530312/65904139-abd2b300-e372-11e9-9c43-5d65ae2aa5dd.png)

**Comment by charliearcuri** [comment]
WORKAROUND:
Rather than double-clicking the .VSIX once you've downloaded it, go into VS Code -> Extensions (left pane - looks like a 4 piece puzzle) -> ellipsis (…) -> Install from VSIX...

**Comment by charliearcuri** [comment]
Close issue because there's a workaround (install from within VS Code.)

**Comment by charliearcuri** [comment]
also, the readme.md in the musupport\release folder shows how to install... :)

**Comment by jorticus** [comment]
Your workaround is the preferred method for installing VSIX extensions in VSCode :)
https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

My guess is VSCode decided to re-use the VSIX format, but didn't register with the actual file type so double clicking it attempts to install it in the full Visual Studio.
